#
# Projetk: proj1.tex
# Author: Dalibor Kralik
# Datum 24.2.2022
#

all: proj2 clear


proj2:
	latex proj2.tex
	latex proj2.tex
	dvips proj2.dvi
	ps2pdf proj2.ps

clear:
	rm *.out *.aux *.ps *.dvi *.log

